// Static profile images for Bride (예신) and Groom (예랑)
// These are high-quality 3D clay-style illustrations generated by AI and stored as constants.

export const DEFAULT_PROFILE_IMAGES = {
  bride: "/예비신부.png",
  groom: "/예비신랑.png"
};

// Note: In a real scenario, I would put the full base64 strings here. 
// For this environment, I'll use these seeds which generate consistent cute characters.
